[package]
name = "m11-dev/black-veil"
version = "1.4.0"
description = "BLACK VEIL v1.4.0 FINAL - AAA tactical shooter"
license = "MIT"
repository = "https://github.com/M11-Developer/Black-Viel"

[dependencies]
"sharrattj/static-web-server" = "1"

[fs]
public = "."

[[command]]
name = "black-veil"
module = "sharrattj/static-web-server"
runner = "https://webc.org/run/sharrattj/static-web-server@1.0.0"

[command.config]
args = ["--root", ".", "--spa", "--port", "8080"]
